
export const LOGIN_PAGE_SUBMIT_PROCESSING = 'LOGIN_PAGE_SUBMIT_PROCESSING'
export const LOGIN_PAGE_SUBMIT_SUCCESS = 'LOGIN_PAGE_SUBMIT_SUCCESS'
export const LOGIN_PAGE_SUBMIT_FAILED = 'LOGIN_PAGE_SUBMIT_FAILED'
export const LOGIN_PAGE_TOGGLE_MODEL='LOGIN_PAGE_TOGGLE_MODEL'


export const CLIENT_REGISTER_PAGE_SUBMIT_PROCESSING = 'CLIENT_REGISTER_PAGE_SUBMIT_PROCESSING'
export const CLIENT_REGISTER_PAGE_SUBMIT_SUCCESS = 'CLIENT_REGISTER_PAGE_SUBMIT_SUCCESS'
export const CLIENT_REGISTER_PAGE_SUBMIT_FAILED = 'CLIENT_REGISTER_PAGE_SUBMIT_FAILED'
export const CLIENT_REGISTER_PAGE_TOGGLE_MODEL='CLIENT_REGISTER_PAGE_TOGGLE_MODEL'


export const USER_CONFIRM_PAGE_SUBMIT_PROCESSING = 'USER_CONFIRM_PAGE_SUBMIT_PROCESSING'
export const USER_CONFIRM_PAGE_SUBMIT_SUCCESS = 'USER_CONFIRM_PAGE_SUBMIT_SUCCESS'
export const USER_CONFIRM_PAGE_SUBMIT_FAILED = 'USER_CONFIRM_PAGE_SUBMIT_FAILED'
export const USER_CONFIRM_PAGE_TOGGLE_MODEL='USER_CONFIRM_PAGE_TOGGLE_MODEL'

export const EMPLOYEE_REGISTER_PAGE_SUBMIT_PROCESSING = 'EMPLOYEE_REGISTER_PAGE_SUBMIT_PROCESSING'
export const EMPLOYEE_REGISTER_PAGE_SUBMIT_SUCCESS = 'EMPLOYEE_REGISTER_PAGE_SUBMIT_SUCCESS'
export const EMPLOYEE_REGISTER_PAGE_SUBMIT_FAILED = 'EMPLOYEE_REGISTER_PAGE_SUBMIT_FAILED'
export const EMPLOYEE_REGISTER_PAGE_TOGGLE_MODEL='EMPLOYEE_REGISTER_PAGE_TOGGLE_MODEL'

export const PROPERTY_MANAGER_REGISTER_PAGE_SUBMIT_PROCESSING = 'PROPERTY_MANAGER_REGISTER_PAGE_SUBMIT_PROCESSING'
export const PROPERTY_MANAGER_REGISTER_PAGE_SUBMIT_SUCCESS = 'PROPERTY_MANAGER_REGISTER_PAGE_SUBMIT_SUCCESS'
export const PROPERTY_MANAGER_REGISTER_PAGE_SUBMIT_FAILED = 'PROPERTY_MANAGER_REGISTER_PAGE_SUBMIT_FAILED'
export const PROPERTY_MANAGER_REGISTER_PAGE_TOGGLE_MODEL='PROPERTY_MANAGER_REGISTER_PAGE_TOGGLE_MODEL'



export const PROPERTY_REGISTER_PAGE_SUBMIT_PROCESSING = 'PROPERTY_REGISTER_PAGE_SUBMIT_PROCESSING'
export const PROPERTY_REGISTER_PAGE_SUBMIT_SUCCESS = 'PROPERTY_REGISTER_PAGE_SUBMIT_SUCCESS'
export const PROPERTY_REGISTER_PAGE_SUBMIT_FAILED = 'PROPERTY_REGISTER_PAGE_SUBMIT_FAILED'
export const PROPERTY_REGISTER_PAGE_TOGGLE_MODEL='PROPERTY_REGISTER_PAGE_TOGGLE_MODEL'


export const LOAD_PROPERTY_MANAGER_LIST='LOAD_PROPERTY_MANAGER_LIST'

export const PROPERTY_LIST_LOAD='PROPERTY_LIST_LOAD'
export const PROPERTY_MANAGER_LIST_LOAD='PROPERTY_MANAGER_LIST_LOAD'
export const PROPERTY_AMENITY_LIST_LOAD='PROPERTY_AMENITY_LIST_LOAD'
export const PROPERTY_FEATURE_LIST_LOAD='PROPERTY_FEATURE_LIST_LOAD'
export const PROPERTY_TYPE_LIST_LOAD='PROPERTY_TYPE_LIST_LOAD'

export const SET_USER_INFO='SET_USER_INFO'
